language: java

jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8

matrix:
  allow_failures:
    include:
      - jdk: oraclejdk8
        install: ./gradlew help
        script: ./gradlew help

    - jdk: oraclejdk8
    - jdk: openjdk8
