language: java

jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8

matrix:
  include:
    - jdk: oraclejdk8
      install: ./gradlew -PprojectJavaVersion=1.8 assemble
      script: ./gradlew -PprojectJavaVersion=1.8 check

  allow_failures:
    - jdk: oraclejdk8
    - jdk: openjdk8
