language: java

#jdk:
#  - oraclejdk8
#  - oraclejdk9
#  - openjdk8

matrix:
  include:
    - jdk: oraclejdk8
    - jdk: oraclejdk9
    - jdk: openjdk8

  allow_failures:
    - jdk: oraclejdk8
    - jdk: openjdk8
