language: java

jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8

matrix:
  include:
    - jdk: oraclejdk8
      install: ./gradlew help
      script: ./gradlew help
  allow_failures:
    - jdk: oraclejdk8
    - jdk: openjdk8
