language: java

#jdk:
#  - oraclejdk9

matrix:
  include:
    - jdk: oraclejdk9
    - jdk: openjdk9

    - jdk: oraclejdk8
      install: ./gradlew -PprojectJavaVersion=1.8 assemble
      script: ./gradlew -PprojectJavaVersion=1.8 check

    - jdk: openjdk8
      install: ./gradlew -PprojectJavaVersion=1.8 assemble
      script: ./gradlew -PprojectJavaVersion=1.8 check

  allow_failures:
    - jdk: oraclejdk8
    - jdk: openjdk8
