language: java

matrix:
  include:
    - jdk: oraclejdk9
      install: ./gradlew -PprojectJavaVersion=1.9 assemble
      script: ./gradlew -PprojectJavaVersion=1.9 check

    - jdk: openjdk8
      install: ./gradlew -PprojectJavaVersion=1.8 assemble
      script: ./gradlew -PprojectJavaVersion=1.8 check

  allow_failures:
    - jdk: openjdk8
